# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-12 02:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllJobTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AllLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(default=None, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AllParsedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('header', models.CharField(max_length=500, null=True)),
                ('url', models.CharField(max_length=500)),
                ('school', models.CharField(max_length=500, null=True)),
                ('school_program', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=250)),
                ('current_school', models.CharField(choices=[('uoft', 'University of Toronto'), ('harvard', 'Harvard'), ('MIT', 'MIT'), ('waterloo', 'Univertsity of Waterloo')], default='uoft', max_length=100)),
                ('school_program', models.CharField(choices=[('computer_science', 'Computer Science'), ('commerce', 'Commerce'), ('medicine_lifesci', 'Medicine/Lifesci/Healthsci'), ('math_statistics', 'Math/Statistics/Physics')], default='computer_science', max_length=100)),
                ('school_of_interest', models.CharField(choices=[('uoft', 'University of Toronto'), ('harvard', 'Harvard'), ('MIT', 'MIT'), ('waterloo', 'Univertsity of Waterloo')], default='uoft', max_length=100)),
                ('industry_of_interest', models.CharField(choices=[('software', 'software'), ('entrepreneur', 'entrepreneur'), ('data_science', 'data science'), ('research', 'research'), ('finance', 'finance'), ('medicine', 'medicine')], default='software', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='alllocation',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_rec.AllParsedProfile'),
        ),
        migrations.AddField(
            model_name='alljobtitle',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_rec.AllParsedProfile'),
        ),
    ]
