# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_rec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allparsedprofile',
            name='industry_classification',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='allparsedprofile',
            name='program_classification',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_school',
            field=models.CharField(choices=[('uoft', 'University of Toronto'), ('harvard', 'Harvard University'), ('mit', 'Massachusetts Institute of Technology'), ('waterloo', 'Univertsity of Waterloo'), ('stanford', 'Stanford University'), ('western', 'Western University'), ('ucb', 'University of California, Berkeley'), ('caltech', 'Caltech'), ('cornell', 'Cornell University'), ('oxford', 'Oxford University'), ('cmu', 'Carnegie Mellon University'), ('upenn', 'University of Pennsylvania'), ('cambridge', 'University of Cambridge'), ('ucla', 'University of California, Los Angeles'), ('queens', "Queen's University"), ('columbia', 'Columbia University')], default='uoft', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry_of_interest',
            field=models.CharField(choices=[('software', 'Software'), ('engineering', 'Engineering, excluding Software'), ('research', 'Research'), ('design', 'Design'), ('data_science', 'Data Science'), ('product_manager', 'Product Manager'), ('business_finance', 'Business and Finance'), ('startup_founder', 'Startup Founders/Executives'), ('admin_coordination', 'Startup Founders/Executives'), ('startup_founder', 'Admin/Coordination/IT/HR'), ('crypto_blockchain', 'Cryptography/Blockchain')], default='software', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_of_interest',
            field=models.CharField(choices=[('uoft', 'University of Toronto'), ('harvard', 'Harvard University'), ('mit', 'Massachusetts Institute of Technology'), ('waterloo', 'Univertsity of Waterloo'), ('stanford', 'Stanford University'), ('western', 'Western University'), ('ucb', 'University of California, Berkeley'), ('caltech', 'Caltech'), ('cornell', 'Cornell University'), ('oxford', 'Oxford University'), ('cmu', 'Carnegie Mellon University'), ('upenn', 'University of Pennsylvania'), ('cambridge', 'University of Cambridge'), ('ucla', 'University of California, Los Angeles'), ('queens', "Queen's University"), ('columbia', 'Columbia University')], default='uoft', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_program',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('commerce_business', 'Commerce/Business/Finance'), ('humanities_lifesci', 'Humanities/LifeSci/HealthSci'), ('math_physics_statistics', 'Math/Physics/Statistics'), ('engineering', 'Engineering')], default='computer_science', max_length=100),
        ),
    ]
