# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-30 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_rec', '0002_auto_20170630_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='industry_interest',
            field=models.CharField(choices=[('software', 'software'), ('entrepreneur', 'entrepreneur'), ('research', 'research'), ('finance', 'finance')], default='software', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(choices=[('uoft', 'university of toronto'), ('harvard', 'Harvard'), ('MIT', 'MIT'), ('waterloo', 'Univertsity of Waterloo')], default='uoft', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_program',
            field=models.CharField(choices=[('computer_science', 'computer_science'), ('commerce', 'commerce'), ('medicine_lifesci', 'medicine_lifesci'), ('math', 'math')], default='computer_science', max_length=100),
        ),
    ]
