# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_rec', '0002_auto_20170728_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allparsedprofile',
            name='industry_classification',
        ),
        migrations.AddField(
            model_name='alljobtitle',
            name='job_classification',
            field=models.IntegerField(null=True),
        ),
    ]
