# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_rec', '0003_auto_20170728_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allparsedprofile',
            name='program_classification',
            field=models.IntegerField(null=True),
        ),
    ]
