# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_rec', '0003_auto_20170630_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='school',
        ),
        migrations.AddField(
            model_name='profile',
            name='current_school',
            field=models.CharField(choices=[('uoft', 'University of Toronto'), ('harvard', 'Harvard'), ('MIT', 'MIT'), ('waterloo', 'Univertsity of Waterloo')], default='uoft', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='name', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='school_of_interest',
            field=models.CharField(choices=[('uoft', 'University of Toronto'), ('harvard', 'Harvard'), ('MIT', 'MIT'), ('waterloo', 'Univertsity of Waterloo')], default='uoft', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='industry_interest',
            field=models.CharField(choices=[('software', 'software'), ('entrepreneur', 'entrepreneur'), ('data_science', 'data science'), ('research', 'research'), ('finance', 'finance'), ('medicine', 'medicine')], default='software', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_program',
            field=models.CharField(choices=[('computer_science', 'Computer Science'), ('commerce', 'Commerce'), ('medicine_lifesci', 'Medicine/Lifesci/Healthsci'), ('math_statistics', 'Math/Statistics/Physics')], default='computer_science', max_length=100),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
