# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-31 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link_rec', '0004_auto_20170728_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_school',
            field=models.CharField(choices=[('university_of_toronto', 'University of Toronto'), ('harvard', 'Harvard University'), ('massachusetts_institute_of_technology', 'Massachusetts Institute of Technology'), ('waterloo', 'University of Waterloo'), ('stanford', 'Stanford University'), ('western', 'Western University'), ('university_of_california_berkeley', 'University of California, Berkeley'), ('caltech', 'Caltech'), ('cornell', 'Cornell University'), ('oxford', 'Oxford University'), ('carnegie_mellon_university', 'Carnegie Mellon University'), ('university_of_pennsylvania', 'University of Pennsylvania'), ('cambridge', 'University of Cambridge'), ('university_of_california_los_angeles', 'University of California, Los Angeles'), ('queens', "Queen's University"), ('columbia', 'Columbia University')], default='university_of_toronto', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school_of_interest',
            field=models.CharField(choices=[('university_of_toronto', 'University of Toronto'), ('harvard', 'Harvard University'), ('massachusetts_institute_of_technology', 'Massachusetts Institute of Technology'), ('waterloo', 'University of Waterloo'), ('stanford', 'Stanford University'), ('western', 'Western University'), ('university_of_california_berkeley', 'University of California, Berkeley'), ('caltech', 'Caltech'), ('cornell', 'Cornell University'), ('oxford', 'Oxford University'), ('carnegie_mellon_university', 'Carnegie Mellon University'), ('university_of_pennsylvania', 'University of Pennsylvania'), ('cambridge', 'University of Cambridge'), ('university_of_california_los_angeles', 'University of California, Los Angeles'), ('queens', "Queen's University"), ('columbia', 'Columbia University')], default='university_of_toronto', max_length=100),
        ),
    ]
