# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-05 04:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_rec', '0004_auto_20170705_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='industry_interest',
            new_name='industry_of_interest',
        ),
    ]
