# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-07 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link_rec', '0005_auto_20170705_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsedProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url', models.CharField(max_length=500)),
                ('header', models.CharField(max_length=500)),
                ('school', models.CharField(max_length=500)),
                ('school_program', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('parsedprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='link_rec.ParsedProfile')),
                ('exp1', models.CharField(max_length=500)),
                ('exp2', models.CharField(max_length=500)),
                ('exp3', models.CharField(max_length=500)),
                ('exp4', models.CharField(max_length=500)),
                ('exp5', models.CharField(max_length=500)),
                ('exp6', models.CharField(max_length=500)),
                ('exp7', models.CharField(max_length=500)),
                ('exp8', models.CharField(max_length=500)),
                ('exp9', models.CharField(max_length=500)),
            ],
            bases=('link_rec.parsedprofile',),
        ),
        migrations.AddField(
            model_name='parsedprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
